### ISSUE TITLE
How to reduce spacing between character in the subtitle, h1

### ISSUE THREAD

**Issue by pegasusearl** [kaeyleo/jekyll-theme-H2O#31]
How to reduce spacing between character in the subtitle, h1?
This doesn't look good for latin.
[https://pasteboard.co/GSx0ZB9.png](https://pasteboard.co/GSx0ZB9.png)
![attached-image](https://cdn.pbrd.co/images/GSx0ZB9.png)

Thank you.

**Comment by eastpiger** [comment]
At [Line 125 in file dev/sass/common.scss](https://github.com/kaeyleo/jekyll-theme-H2O/blob/688f37fc7467fd75ff8ed34e28087f7781a29371/dev/sass/common.scss#L125)

``` scss
    h3 {
        font-size: 20px;
        font-weight: normal;
        letter-spacing: 10px;
        margin-top: 8px;
    }
```
